### ISSUE TITLE
Ulejváci omg

### ISSUE THREAD

**Issue by charamza** [herovis/Zelda#2]
@AtonDuke  @Petonika  @xXxCaseyGFLxXx  @otasek123 

Zkouším kdo jak dává pozor vy ulejváci. Ten co se ozve jako poslední dostane nejvíc práce.

**Comment by CaseyGFL** [comment]
Jsem tu xd

Dne 12. 6. 2017 8:44 AM napsal uživatel "Honza Charamza" <
notifications@github.com>:

**Comment by otasek123** [comment]
omgomgomgomgomgomgomg
