### ISSUE TITLE
OMFG, alright.

### ISSUE THREAD

**Issue by AtonDuke** [herovis/Zelda#3]
Vrhnu se na to co nejdřív to půjde.
Asi zítra o prográmku.

**Comment by charamza** [comment]
@AtonDuke Nemusíš kvůli tomu otevírat issue, ale když už jsme u toho, zkus začít už dneska doma, nebo aspoň ty tvoje návrhy naházej do wiki tady na githubu, aby to vypadalo že aspoň něco děláš.

**Comment by AtonDuke** [comment]
Sorry, psal jsem to narychlo na mobilu.

**Comment by AtonDuke** [comment]
I'm a fucking noob on github.

**Comment by charamza** [comment]
Komunikuj prosímtě v Českém jazyce. Každopádně zkus se na to pak kouknout, ať na tom nevisíme.
